Размер фотографии и слайдер фильтров
htmlacademy-javascript/253339-kekstagram-23 pull request #7
Opened 2021-06-29 12:36 UTC by KamilMiller

2021-06-29 13:13 UTC, o-bender requested changes

2021-06-29 13:13 UTC, o-bender commented on js/effects-control.js
> +      range: {
вот эти штуки перенеси в effectsData вроде такого:
effectsData = {
    chrome: {
        name: 'chrome',
        property: 'grayscale',
        unit: '',
        options: {
           range: {
             min: 0,
             max: 1,
           },
           step: 0.1,
           start: 1,  // это вместо sliderElement.noUiSlider.set(1);
        }
    },
}

sliderElement.noUiSlider.updateOptions(effectsData['chrome'].options);

можешь ещё попробовать что-то вроде
sliderElement.noUiSlider.updateOptions(effectsData[filter.target.id].options)

2021-06-29 13:13 UTC, o-bender commented on js/effects-control.js
> +  for (let i = 1; i < arr.length; i++) {
используй for of

2021-06-29 13:13 UTC, o-bender commented on js/effects-control.js
> +      uploadedPicture.style.filter = `${arr[i].property}(${value}${arr[i].unit})`;
мб тут  break добавить? я так понимаю один раз зашли в if и повторного захода не будет. так что лишние итерации ждать смысла нет.

2021-06-29 13:13 UTC, o-bender commented on js/image-resize.js
> +scaleControlSmaller.addEventListener('click', () => {
эта и следующая функции прям копипаста:)
Посмотри мб так покажется лучше:
```
const MAX_SCALE = 1;
const MIN_SCALE = 0.25;
const scaleDicrections = {
    up: 1,
    down: -1,
}

const changeScale = (direction) => {
    if (direction === scaleDicrections.up && scaleIndex < MAX_SCALE 
     || direction === scaleDicrections.down && scaleIndex > MIN_SCALE) {
       scaleIndex += RESIZE_SCALE_INCREMENT * direction;
       uploadedPicture.style.transform = `scale(${scaleIndex})`;
       scaleControlValue.value = `${scaleIndex * 100}%`;
    }
}


```

2021-06-29 13:13 UTC, o-bender commented on js/image-resize.js
> +  if (scaleIndex < 1) {
единицу надо в константы вынести

2021-06-29 14:54 UTC, KamilMiller commented on js/effects-control.js
> +      for (let i = 1; i < effectsData.length; i++) {
Мне нужно обойти не все элементы -- первый нужно пропустить, начать со второго. 
Подойдет ли `for ... of` для этих целей?

2021-06-29 15:18 UTC, KamilMiller commented on js/effects-control.js
> +      range: {
В твоей версии effectsData становится объектом. У меня он массив, мне нужно итерироваться по нему при переключении фильтров. 

Можно попробовать сделать так:
```
effectsData = [
  chrome: {
    name: 'chrome',
  },
]
```

2021-06-29 15:26 UTC, KamilMiller commented on js/effects-control.js
> +  for (let i = 1; i < arr.length; i++) {
Здесь та же проблема, что и выше.
`for ... of` начнет с первого элемента, а мне нужно начинать со второго.

2021-06-29 16:15 UTC, o-bender commented on js/effects-control.js
> +      for (let i = 1; i < effectsData.length; i++) {
Тут можно либо воспользоваться слайсом. Либо просто вынести первый элемент (это ж отсутствие эффекта) в отдельную константу. Но так это не критично. Мне просто for of внешне больше нравится)

2021-06-29 16:20 UTC, o-bender commented on js/effects-control.js
> +      range: {
на сколько я вижу ты используешь только параметр name:
```
        if (evt.target.matches(`#effect-${effectsData[i].name}`)) {
          uploadedPicture.removeAttribute('class');
          uploadedPicture.classList.add(`effects__preview--${effectsData[i]}`); // тут похоже забыл name
        }
```

так что можно сделать так:
```

const effectsData = {
   chrome: {}
}
for (const effect in effectsData) {
        if (evt.target.matches(`#effect-${effect}`)) {
          uploadedPicture.removeAttribute('class');
          uploadedPicture.classList.add(`effects__preview--${effect}`);
        }
}
```

2021-06-29 16:21 UTC, o-bender commented on js/effects-control.js
> +  for (let i = 1; i < arr.length; i++) {
тот же ответ, что и выше)

2021-06-29 20:58 UTC, KamilMiller commented on js/effects-control.js
> +      range: {
Ну как же, я использую не только name. Все ключи используются -- и options, и property, и unit (см. строку 124). Если имя эффекта (они ведь все разные) будет единственным ключом у всех элементов массива effectsData, тогда как добраться до свойств options, property, unit при проходе по этому массиву?

2021-06-30 09:40 UTC, o-bender commented on js/effects-control.js
> +      range: {
Как всегда: 
const effectsData = {
   chrome: {
      options: 123
   }
}
effectsData[effectName]['options']
effectsData[effectName].options

2021-06-30 15:37 UTC, merged